### ISSUE TITLE
Is there a way to add just MDCTextField to my podfile to preserve the memory of my app?

### ISSUE THREAD

**Issue by kristinamartinkevich** [material-components/material-components-ios#10025]

**Comment by kristinamartinkevich** [comment]
adding
```
pod 'MaterialComponents/TextFields'
pod 'MaterialComponents/TextFields+ColorThemer'
```
shows an error

**Comment by kristinamartinkevich** [comment]
as well as 
`pod 'MaterialComponents/TextFields+Theming'`

**Comment by andrewoverton** [comment]
Hello @kristinamartinkevich , what error are you getting? When I add this to the podfile of an empty project I have no issues:
```
pod 'MaterialComponents/TextFields'
pod 'MaterialComponents/TextFields+ColorThemer'
```

**Comment by kristinamartinkevich** [comment]
`pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E287)
       Xcode :  ()
         Git : git version 2.24.2 (Apple Git-127)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ f7522d7d6d256180e20ea58e4993652bde690e46

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Slush' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!
  use_modular_headers!
  
  # Pods for Slush
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'MaterialComponents/TextFields'
pod 'MaterialComponents/TextFields+ColorThemer'
end
```

### Error

```
JSON::ParserError - 434: unexpected token at '{
      "name": "MaskedTransition",
      "platforms": {
        "ios": "8.0"
      },
      "public_header_files": "components/MaskedTransition/src/*.h",
      "source_files": [
        "components/MaskedTransition/src/*.{h,m}",
        "components/MaskedTransition/src/private/*.{h,m}"
      ],
      "dependencies": {
        "MotionTransitioning": [
          "~> 5.0"
        ],
        "MotionAnimator": [
          "~> 2.0"
        ],
        "MotionInterc'
/Library/Ruby/Gems/2.6.0/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
/Library/Ruby/Gems/2.6.0/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/specification.rb:742:in `from_string'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/specification.rb:716:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/source.rb:186:in `specification'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver/lazy_specification.rb:29:in `subspec_by_name'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:362:in `block in specifications_for_dependency'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:362:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:362:in `specifications_for_dependency'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:165:in `search_for'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:267:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:267:in `sort_by'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/update.rb:63:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=434%3A+unexpected+token+at+%27%7B%0A++++++%22name%22%3A+%22MaskedTransition%22%2C%0A++++++%22platforms%22%3A+%7B%0A++++++++%22ios%22%3A+%228.0%22%0A++++++%7D%2C%0A++++++%22public_header_files%22%3A+%22components%2FMaskedTransition%2Fsrc%2F%2A.h%22%2C%0A++++++%22source_files%22%3A+%5B%0A++++++++%22components%2FMaskedTransition%2Fsrc%2F%2A.%7Bh%2Cm%7D%22%2C%0A++++++++%22components%2FMaskedTransition%2Fsrc%2Fprivate%2F%2A.%7Bh%2Cm%7D%22%0A++++++%5D%2C%0A++++++%22dependencies%22%3A+%7B%0A++++++++%22MotionTransitioning%22%3A+%5B%0A++++++++++%22~%3E+5.0%22%0A++++++++%5D%2C%0A++++++++%22MotionAnimator%22%3A+%5B%0A++++++++++%22~%3E+2.0%22%0A++++++++%5D%2C%0A++++++++%22MotionInterc%27&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

[!] Automatically assigning platform `iOS` with version `11.0` on target `Slush` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.`

**Comment by kristinamartinkevich** [comment]
Hello, Maybe i need to delete material components' pod all together first.

**Comment by andrewoverton** [comment]
Maybe try running [this command](https://github.com/CocoaPods/CocoaPods/issues/9260#issuecomment-542586026)? It's worked for other people in the past with similar issues.

**Comment by bryanoltman** [comment]
Closing due to inactivity. Please reopen if this is still an issue.
