### ISSUE TITLE
Can't "pod install" the Catalog project

### ISSUE THREAD

**Issue by bernaferrari** [material-components/material-components-ios#2493]
I can't manage to run the Catalog project (from latest version, on Master) in CocoaPods; other projects ran fine. I tried even updating CocoaPods to 1.3.1, but didn't fix anything.

Steps to reproduce:
1: Download the full project
2: cd to Catalog's folder
3: pod install

I attached the full logs below in a file.

```
LoadError - cannot load such file -- /Users/bernardoferrari/Downloads/material-components-ios-develop-2/catalog/third_party/EarlGrey/gem/lib/earlgrey/configure_earlgrey.rb
/Users/bernardoferrari/Downloads/material-components-ios-develop-2/catalog/Podfile:75:in `load'
/Users/bernardoferrari/Downloads/material-components-ios-develop-2/catalog/Podfile:75:in `block (2 levels) in from_ruby'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:619:in `run_podfile_post_install_hook'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:607:in `block in run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:606:in `run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:185:in `block in generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:182:in `generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:119:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

[pod error.txt](https://github.com/material-components/material-components-ios/files/1489540/pod.error.txt)

**Comment by romoore** [comment]
Hi @bernaferrari . Thanks for using MDC-iOS!  I tried your steps and it seems that the problem is downloading the .ZIP archive from GitHub.  If you `git clone` instead, everything should work correctly.  

The problem is that our EarGrey script assumes that it is in a git repository and tries to perform a "submodule update":

```ruby
 # EarlGrey configuration
  earl_grey_dir = "#{File.dirname(__FILE__)}/third_party/EarlGrey"
  `git submodule update --init #{earl_grey_dir}`
  load "#{earl_grey_dir}/gem/lib/earlgrey/configure_earlgrey.rb"
  configure_for_earlgrey(installer, PROJECT_NAME, TEST_TARGET, SCHEME_FILE)
```

I will talk to the team about supporting archive downloads, but in the mean time, could you try again with a "git clone" instead? If you're not working with a fork (for contributing), then it should be a one-liner:

```bash
git clone https://github.com/material-components/material-components.git
```

**Comment by bernaferrari** [comment]
Worked fine, thanks! I would never have guessed there was as difference between downloading and cloning.

**Comment by romoore** [comment]
Sorry for any confusion. 😕  I'll take a look at making our Podfile a bit more robust, since the EarlGrey tests aren't strictly necessary for building the Catalog app.
