### ISSUE TITLE
{kokoro} Pin to Cocoapods 1.5.3

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#6574]
Until we can get support for CocoaPods 1.6, our kokoro jobs should pin to Cocoapods 1.5.3.

```
Generating Pods project
[!] An error occurred while processing the post-install hook of the Podfile.

No such file or directory @ rb_sysopen - /Volumes/BuildData/tmpfs/src/github/repo/catalog/Pods/Target Support Files/MaterialComponents/MaterialComponents.unit.xcconfig

/Volumes/BuildData/tmpfs/src/github/repo/catalog/Podfile:122:in `read'
/Volumes/BuildData/tmpfs/src/github/repo/catalog/Podfile:122:in `block (3 levels) in from_ruby'
/Volumes/BuildData/tmpfs/src/github/repo/catalog/Podfile:121:in `each'
/Volumes/BuildData/tmpfs/src/github/repo/catalog/Podfile:121:in `block (2 levels) in from_ruby'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/cocoapods-core-1.6.0/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:701:in `run_podfile_post_install_hook'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:689:in `block in run_podfile_post_install_hooks'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.0/lib/cocoapods/user_interface.rb:145:in `message'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:688:in `run_podfile_post_install_hooks'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:211:in `block in generate_pods_project'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:208:in `generate_pods_project'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:139:in `install!'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.0/lib/cocoapods/command/install.rb:48:in `run'
/Users/kbuilder/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:52:in `run'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/bin/pod:23:in `load'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/bin/pod:23:in `<main>'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
Traceback (most recent call last):
  File "/tmpfs/src/github/repo/scripts/manage_pods.py", line 217, in <module>
    main()
  File "/tmpfs/src/github/repo/scripts/manage_pods.py", line 203, in main
    install_all_podfile_dirs(args.directory, args.fast_pod_install, BLACKLIST_DIRS)
  File "/tmpfs/src/github/repo/scripts/manage_pods.py", line 105, in install_all_podfile_dirs
    install_podfile_dir(d, fast_install)
  File "/tmpfs/src/github/repo/scripts/manage_pods.py", line 92, in install_podfile_dir
    subprocess.check_call(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pod', 'install', '--project-directory=./catalog']' returned non-zero exit status 1
```

**Comment by bernaferrari** [comment]
I just donwloaded Material Components and had same issue when using CocoaPods 1.6.0.
