### ISSUE TITLE
[Releasing] Travis-CI is failing

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#6597]
Travis-CI is failing with the current develop and stable branches.

Investigate and fix or remove.

---
#### Internal data
- Associated internal bug: [b/124241211](http://b/124241211)

**Comment by romoore** [comment]
@ianegordon Could you please copy-paste relevant log portions or link to the logs?

**Comment by ianegordon** [comment]
Failing PR:
https://github.com/material-components/material-components-ios/pull/6571

Travis Log:
https://travis-ci.org/material-components/material-components-ios/builds/490277575?utm_source=github_status&utm_medium=notification

**Comment by romoore** [comment]
```
Generating Pods project
[!] An error occurred while processing the post-install hook of the Podfile.
No such file or directory @ rb_sysopen - /Users/travis/build/material-components/material-components-ios/catalog/Pods/Target Support Files/MaterialComponents/MaterialComponents.unit.xcconfig
/Users/travis/build/material-components/material-components-ios/catalog/Podfile:122:in `read'
/Users/travis/build/material-components/material-components-ios/catalog/Podfile:122:in `block (3 levels) in from_ruby'
/Users/travis/build/material-components/material-components-ios/catalog/Podfile:121:in `each'
/Users/travis/build/material-components/material-components-ios/catalog/Podfile:121:in `block (2 levels) in from_ruby'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-core-1.6.0/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:701:in `run_podfile_post_install_hook'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:689:in `block in run_podfile_post_install_hooks'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0/lib/cocoapods/user_interface.rb:145:in `message'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:688:in `run_podfile_post_install_hooks'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:211:in `block in generate_pods_project'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:208:in `generate_pods_project'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:139:in `install!'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0/lib/cocoapods/command/install.rb:48:in `run'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:52:in `run'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>'
/Users/travis/.rvm/gems/ruby-2.4.2/bin/pod:23:in `load'
/Users/travis/.rvm/gems/ruby-2.4.2/bin/pod:23:in `<main>'
/Users/travis/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
/Users/travis/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
Traceback (most recent call last):
  File "/Users/travis/build/material-components/material-components-ios/scripts/manage_pods.py", line 217, in <module>
    main()
  File "/Users/travis/build/material-components/material-components-ios/scripts/manage_pods.py", line 203, in main
    install_all_podfile_dirs(args.directory, args.fast_pod_install, BLACKLIST_DIRS)
  File "/Users/travis/build/material-components/material-components-ios/scripts/manage_pods.py", line 105, in install_all_podfile_dirs
    install_podfile_dir(d, fast_install)
  File "/Users/travis/build/material-components/material-components-ios/scripts/manage_pods.py", line 92, in install_podfile_dir
    subprocess.check_call(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pod', 'install', '--project-directory=./catalog']' returned non-zero exit status 1
The command "scripts/prep_all" exited with 1.
23.40s$ travis_wait scripts/build_all --verbose
Still running (1 of 20): scripts/build_all --verbose
The command scripts/build_all --verbose exited with 1.
Log:
xcodebuild  MDCCatalog in /Users/travis/build/material-components/material-components-ios/scripts/../catalog/MDCCatalog.xcworkspace.
▸ Building MDCCatalog/MDCActionExtension [Debug]
▸ Check Dependencies
▸ Running script '[CP] Check Pods Manifest.lock'
❌  error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

```

**Comment by romoore** [comment]
The current `release-candidate` branch is passing on Travis. The issues may have been resolved in the latest release.

https://travis-ci.org/material-components/material-components-ios/jobs/493384854
