### ISSUE TITLE
[Demos] Shrine builds failing in Xcode 10.1 CocoaPods Kokoro job

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#7264]
```
> Build Succeeded
xcodebuild  Shrine in /tmpfs/src/github/repo/scripts/../demos/Shrine/Shrine.xcworkspace.
/Users/kbuilder/.rvm/gems/ruby-2.5.1/gems/xcpretty-0.3.0/lib/xcpretty/parser.rb:434:in `===': invalid byte sequence in US-ASCII (ArgumentError)
	from /Users/kbuilder/.rvm/gems/ruby-2.5.1/gems/xcpretty-0.3.0/lib/xcpretty/parser.rb:434:in `update_test_state'
	from /Users/kbuilder/.rvm/gems/ruby-2.5.1/gems/xcpretty-0.3.0/lib/xcpretty/parser.rb:307:in `parse'
	from /Users/kbuilder/.rvm/gems/ruby-2.5.1/gems/xcpretty-0.3.0/lib/xcpretty/formatters/formatter.rb:88:in `pretty_format'
	from /Users/kbuilder/.rvm/gems/ruby-2.5.1/gems/xcpretty-0.3.0/lib/xcpretty/printer.rb:19:in `pretty_print'
	from /Users/kbuilder/.rvm/gems/ruby-2.5.1/gems/xcpretty-0.3.0/bin/xcpretty:84:in `block in <top (required)>'
	from /Users/kbuilder/.rvm/gems/ruby-2.5.1/gems/xcpretty-0.3.0/bin/xcpretty:83:in `each_line'
	from /Users/kbuilder/.rvm/gems/ruby-2.5.1/gems/xcpretty-0.3.0/bin/xcpretty:83:in `<top (required)>'
	from /Users/kbuilder/.rvm/gems/ruby-2.5.1/bin/xcpretty:23:in `load'
	from /Users/kbuilder/.rvm/gems/ruby-2.5.1/bin/xcpretty:23:in `<main>'
	from /Users/kbuilder/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	from /Users/kbuilder/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'


[ID: 2101912] Build finished after 1565 secs, exit value: 1
```

---
#### Internal data
- Associated internal bug: [b/131315804](http://b/131315804)

**Comment by romoore** [comment]
Succeeds locally for me using Xcode 10.0:

```bash
./.kokoro -d cocoapods -c build -t demos/Shrine/...
```

**Comment by andrewoverton** [comment]
@romoore, do you think it could be a ruby version thing? My machine's on 2.3.7.

If this is the issue maybe we could set up RVM.

**Comment by romoore** [comment]
It could be - the kokoro hosts quickly get outdated.

**Comment by romoore** [comment]
Failed again during presubmits for a PR.
